# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "SwiftLane"
  lane :swift_lint do
    swiftlint(
        mode: :lint,
        config_file: ".swiftlint.yml",
        output_file: "fastlane/swiftlint.result.json"
    )
  end
  
  desc "Build"
  lane :build_tests do
    scan()
  end
  
  desc "Reports"
  lane :reports do
    swift_lint
    build_tests
  end
end
